config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, :skip => [:registrations]
  as :user do
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'users' => 'devise/registrations#update', :as => 'user_registration'
  end
  resources :albums do
    resources :posts
  end
  
  get 'albums/:album_id/albums/new' => 'albums#new_album', as: :new_sub_album
  post 'albums/:album_id/albums' => 'albums#create_album', as: :create_sub_album 
  post 'albums/:id/set_private' => 'albums#set_private', as: :set_album_private
    
  root 'albums#index'

end

app/models/album.rb
class Album < ActiveRecord::Base
  has_many :posts, :dependent => :destroy
  has_many :albums, :dependent => :destroy
  belongs_to :album
  validates_presence_of :title
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :album
  mount_uploader :avatar, AvatarUploader
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :authenticate_user!, except: [:show, :index]

  def index
    @albums = Album.where(level: 0)
    @usage = `du -sh`.split()[0] + "B" 
  end

  def show
    @album = Album.find(params[:id])
    if @album.privated
      authenticate_user!
    end 
    @albums = @album.albums
	@album_list = Array.new
	current_album = @album
	while current_album != nil 
      @album_list << current_album
	  current_album = current_album.album
    end
    @album_list.reverse!
    @photos = @album.posts.page(params[:page]).per(12)
  end

  def new
    @album = Album.new
  end
  
  def new_album
    @album = Album.find(params[:album_id])
    @new_album = @album.albums.build
  end
   
  def create
    @album = Album.new(album_params)
    @album.privated = false
    @album.level = 0
    if @album.save
      redirect_to album_path(@album)
    else
      render :new
    end
  end

  def create_album
    @album = Album.find(params[:album_id])
    @new_album = @album.albums.build(album_params)
    @new_album.level = @album.level + 1
    if @new_album.save
      redirect_to album_path(@new_album)
    else
      render :new_album
    end
  end
  
  def set_private
    @album = Album.find(params[:id])
    if @album.privated == true
      @album.update(privated: false)
    else
      @album.update(privated: true)
    end
    redirect_to album_path(@album)
  end
   
  def edit
    @album = Album.find(params[:id])
  end

  def update
    @album = Album.find(params[:id])
    if @album.update(album_params)
      redirect_to album_path(@album)
    else
      render :edit
    end
  end

  def destroy
    @album = Album.find(params[:id])
    @last_album = @album.album
    @album.destroy
    if @last_album != nil
      redirect_to album_path(@last_album)
    else
      redirect_to albums_path
    end
  end

private
  
  def album_params
    params.require(:album).permit(:title, :description)
  end

  def find_album
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_album
  before_action :authenticate_user!
   
  def index
    @photos = Post.all
  end

  def new
    @post = @album.posts.build
  end

  def edit
  end

  def create
    has_photo = false
    params[:images].each do |image|
      @post = @album.posts.create(avatar: image)
      has_photo = true
    end
    
    if has_photo
      current_album = @album
      while current_album != nil
        current_album.update(photo: @post.avatar.url)
        current_album = current_album.album
      end
    end
    redirect_to album_path(@album)
  end

  def upload
  end

  def destroy
  end

private

  def post_params
    params.require(:post).permit(:description, :avatar)
  end

  def find_album
    @album = Album.find(params[:album_id])
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/albums/edit.html.erb
<h1> 編輯相簿 <%= @album.title %> </h1>

<%= simple_form_for(@album) do |f| %>
  <%= f.input :title, input_html: {class: "form-control"} %>
  <%= f.input :description, input_html: {class: "form-control"} %>
  <%= f.submit "Submit", class: "btn btn-primary", data: {disable_with: "Submitting..."} %> 
<% end %> 

app/views/albums/index.html.erb
<h1> 所有相簿 </h1>


<% if current_user %>
  <div class="container col-md-12">
    <h2> <center> <font color="red"> <%= @usage %> </font> / 44GB </center> </h2> 
  </div>
  <div class="container col-md-12">
    <%= link_to "新增相簿", new_album_path, class: "btn btn-primary pull-right" %>
  </div>
<% end %>

<br><br>

<div class="continer col-md-12">
  <% count = 0 %>
  <% is_pair = true %>
  <% @albums.each do |album| %>
    <% if count % 4 == 0 %>
      <div class="row">
      <% is_pair = false %>
    <% end %>
    
    <% if current_user || (!current_user && !album.privated) %>
      <div class="col-md-3">
        <a href="<%= album_path(album) %>" class="thumbnail">
        <% if album.photo != nil %>
          <img src="<%= album.photo %>" class="img-responsive">
        <% else %>
          <img src="/404.gif" class="img-responsive">
        <% end %>
        </a>
        <center>
          <% if album.privated %>
            <p class="label label-danger"> 私人</p> 
          <% end %>
          <%= link_to album.title, album_path(album) %>
        </center>
      </div>

      <% if count % 4 == 3 %>
        <% is_pair = true %>
        </div>
      <% end %>
      <% count = count + 1 %>
    <% end %>
  <% end %>
  <% if !is_pair %>
    </div>
  <% end %>
</div>

app/views/albums/new.html.erb
<h1> 新增相簿 </h1>

<%= simple_form_for(@album) do |f| %>
  <%= f.input :title, input_html: {class: "form-control"} %>
  <%= f.input :description, input_html: {class: "form-control"} %>
  <%= f.submit "Submit", class: "btn btn-primary", data: {disable_with: "Submitting..."} %> 
<% end %> 

app/views/albums/new_album.html.erb
<h1> New Album </h1>

<%= simple_form_for [@new_album], :url => create_sub_album_path, :method => :post do |f| %>
  <%= f.input :title, input_html: {class: "form-control"} %>
  <%= f.input :description, input_html: {class: "form-control"} %>
  <%= f.submit "Submit", class: "btn btn-primary", data: {disable_with: "Submitting..."} %> 
<% end %> 

app/views/albums/show.html.erb
<h1> <% if @album.privated %> <p class="label label-danger">私人</p> <% end %> <%= @album.title %></h1>

<div class="container col-md-12">
  <ol class="breadcrumb">
    <% @album_list.each do |album| %>
      <li> <a href="<%= album_path(album) %>"> <%= album.title %> </a> </li>
    <% end %>
  </ol> 
</div>

<div class="container col-md-12">
  <%= link_to "回首頁", albums_path, class: "btn btn-info" %>
  <% if @album.album != nil %>
    <%= link_to "回上一層", album_path(@album.album), class: "btn btn-default" %>
  <% else %>
    <%= link_to "回上一層", albums_path, class: "btn btn-default" %>
  <% end %>

  <% if current_user && @album.albums.count == 0 %>
    <%= link_to "刪除此相簿", album_path, method: :delete, class: "btn btn-danger pull-right", data: {confirm: "確定要刪除這個相簿嗎？刪掉以後，這個資料夾裡面，「所有的」相簿通通都會不見喔"} %> 
  <% end %>
  <% if current_user %>
    <%= link_to "編輯相簿", edit_album_path(@album), class: "btn btn-warning pull-right" %>
    <% if @album.privated %>
      <%= link_to "設為公開", set_album_private_path(@album), method: :post, class: "btn btn-info pull-right" %>
    <% else %>
      <%= link_to "設為私人", set_album_private_path(@album), method: :post, class: "btn btn-default pull-right" %>
    <% end %>
  <% end %>
</div>

<div class="container col-md-12">
<h3> 相簿 </h3>
<% if current_user %>
  <%= link_to "新增相簿", new_sub_album_path(@album), class: "btn btn-success pull-right" %> 
<% end %>
<div class="continer col-md-12">
  <% count = 0 %>
  <% is_pair = true %>
  <% @albums.each do |album| %>
    <% if count % 4 == 0 %>
      <div class="row">
      <% is_pair = false %>
    <% end %>
    
    <% if current_user || (!current_user && !album.privated) %>
      <div class="col-md-3">
        <a href="<%= album_path(album) %>" class="thumbnail">
        <% if album.photo != nil %>
          <img src="<%= album.photo %>" class="img-responsive">
        <% else %>
          <img src="/404.gif" class="img-responsive">
        <% end %>
        </a>
        <center>
          <% if album.privated %>
            <p class="label label-danger"> 私人</p> 
          <% end %>
          <%= link_to album.title, album_path(album) %>
        </center>
      </div>

      <% if count % 4 == 3 %>
        <% is_pair = true %>
        </div>
      <% end %>
      <% count = count + 1 %>
    <% end %>
  <% end %>
  <% if !is_pair %>
    </div>
  <% end %>
</div>
</div>


<div class="container col-md-12">
<h3> 相片 </h3>
<% if current_user %>
  <%= link_to "新增相片", new_album_post_path(@album), class: "btn btn-primary pull-right" %>
<% end %>
<!-- The container for the list of example images -->
<div class="container col-md-12 links" id="galleries">
  <% count = 0 %>
  <% is_pair = true %>
  <% @photos.each do |photo| %>
    <% if count % 4 == 0 %>
      <div class="row">
      <% is_pair = false %>
    <% end %>
    <div class="col-md-3">
      <a href="<%= photo.avatar.url %>" class="thumbnail">
        <img src="<%= photo.avatar.url %>" class="img-responsive" alt="Cinque Terre">
      </a>
    </div>
    <% if count % 4 == 3 %>
      <% is_pair = true %>
      </div>
    <% end %>
    <% count = count + 1 %>
  <% end %>
  <% if !is_pair %>
    </div>
  <% end %>
</div>
</div>

<%= paginate @photos, :theme => 'twitter-bootstrap-3'%>
<!-- The Gallery as lightbox dialog, should be a child element of the document body -->
<div id="blueimp-gallery" class="blueimp-gallery">
    <div class="slides"></div>
    <h3 class="title"></h3>
    <a class="prev">‹</a>
    <a class="next">›</a>
    <a class="close">×</a>
    <a class="play-pause"></a>
    <ol class="indicator"></ol>
</div>
<script src="/js/blueimp-helper.js"></script>
<script src="/js/blueimp-gallery.js"></script>
<script src="/js/blueimp-gallery-fullscreen.js"></script>
<script src="/js/blueimp-gallery-indicator.js"></script>
<script src="/js/blueimp-gallery-video.js"></script>
<script src="/js/blueimp-gallery-vimeo.js"></script>
<script src="/js/blueimp-gallery-youtube.js"></script>
<script src="/js/vendor/jquery.js"></script>
<script src="/js/jquery.blueimp-gallery.js"></script>
<style>
  .thum {
    max-height: 320px;
    max-width: 240px;
  }
  
  .bg {
    background-size: 100% 100%;
  }
</style>

<script>
document.getElementById('galleries').onclick = function (event) {
    event = event || window.event;
    var target = event.target || event.srcElement,
        link = target.src ? target.parentNode : target,
        options = {index: link, event: event},
        links = this.getElementsByTagName('a');
    blueimp.Gallery(links, options);
};
</script>

app/views/common/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <a class="navbar-brand" href="/"> Album </a>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
              <% if !current_user %> 
				<li> <%= link_to("登入", new_user_session_path) %> </li>
              <% else %>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        Hi!, <%= current_user.email %>
                        <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">
                        <li> <%= link_to("登出", destroy_user_session_path, method: :delete) %> </li>
                    </ul>

                </li>
              <% end %>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Uploader</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="/css/blueimp-gallery.min.css">
</head>

<body>

<%= render "common/navbar" %>
<div class="col-md-2"></div>
<div class="col-md-8">
  <%= yield %>
</div>
<div class="col-md-2"></div>

</body>
</html>

app/views/posts/edit.html.erb
<h1>Posts#edit</h1>
<p>Find me in app/views/posts/edit.html.erb</p>

app/views/posts/index.html.erb
<h1>Posts#index</h1>
<p>Find me in app/views/posts/index.html.erb</p>
<%= link_to "New post", new_post_path, class: "btn btn-primary" %>
<div class="container">
  <% @photos.each do |photo| %>
    <div class="col-md-3">
      <img src="<%= photo.avatar.url %>" class="img-responsive"  alt="Cinque Terre">
    </div>
  <% end %>
</div>

app/views/posts/new.html.erb
<h1> 在 <%= @album.title %> 裡新增相片 </h1>

<%= simple_form_for [@album, @post] do |f| %>
  <%= f.input :description, input_html: { class: "form-control" } %>
  <%= f.file_field :images, multiple: true, name: "images[]" %> 
  <%= f.submit "Submit", class: "btn btn-primary", data: {disable_with: "Submitting..."} %>
<% end %>